name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  coding-checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      - name: "Setup Deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.29.4"
      - name: "Linting"
        run: deno lint
      - name: "Format check"
        run: deno fmt --check
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      - name: "Setup Deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.29.4"
      - name: "unit tests"
        run: deno test --coverage=coverage/profile
      - name: "generate coverage reports"
        run: |
          deno coverage \
            --include=src \
            --exclude=deps \
            --lcov --output=coverage/lcov
      - name: "report coverage"
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov
          gcov: true
