name: Release Next Version
on:
  push:
    branches: [main]
    paths: ["VERSION"]
jobs:
  release:
    name: "Tag Release"
    runs-on: ubuntu-latest
    steps:
      - id: check-out
        name: "Check out code"
        uses: actions/checkout@v3
      - id: current-tag
        name: "Create tag"
        run: |
          echo "version=$(cat VERSION)" >> "${GITHUB_OUTPUT}"
      - id: push-tag
        name: "Push release tag"
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.current-tag.outputs.version}}
          message: "Release ${{ steps.current-tag.outputs.version }}"
