name: Release Next Version
on:
  push:
    branches: [main]
    paths: ["VERSION"]
jobs:
  release:
    name: "Tag Release"
    runs-on: ubuntu-latest
    steps:
      - id: check-out
        name: "Check out code"
        uses: actions/checkout@v3
      - id: current-tag
        name: "Create tag"
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.norely.github.com"

          version="$(cat VERSION)"
          echo "version=${verson}" >> "${GITHUB_OUTPUT}"

          if git rev-parse "v${version}" >/dev/null 2>&1; then
            echo "exists=true" >> "${GITHUB_OUTPUT}"
          fi
      - id: create-tag
        name: "Create release tag"
        if: steps.current-tag.outputs.exists != 'true'
        run: |
          version=$(cat VERSION)
          tag="v${version}"
          msg="Release ${version}"

          git tag -a -m "${msg}" "${tag}"
      - id: push-tag
        name: "Push release tag"
        if: steps.current-tag.outputs.exists != 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          tags: true

