name: Release Next Version
on:
  push:
    branches: [main]
    paths: ["VERSION"]
jobs:
  release:
    name: "Tag Release"
    runs-on: ubuntu-latest
    steps:
      - id: check-out
        name: "Check out code"
        uses: actions/checkout@v3
      - id: current-tag
        name: "Check latest tag"
        run: |
          set -x
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.norely.github.com"

          version="$(cat VERSION)"
          echo "version=${version}" >> "${GITHUB_OUTPUT}"

          if git rev-parse "v${version}" >/dev/null 2>&1; then
            echo "exists=true" >> "${GITHUB_OUTPUT}"
          fi
      - id: push-tag
        name: "Push release tag"
        if: steps.current-tag.outputs.exists != 'true'
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: v${{ steps.current-tag.outputs.version }}
          message: 'Release ${{ steps.current-tag.outputs.version }}'
