name: Prepare a Release PR
on:
  workflow_call: {}

jobs:
  release-pr:
    name: "Release Please"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      - name: "Create/update release PR"
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
